language: minimal

services:
  - docker

install:
  - docker pull jjmerelo/test-perl6

script: docker run -t -v  $TRAVIS_BUILD_DIR:/test --entrypoint "zef install --deps-only . && zef build . && zef test ." jjmerelo/test-perl6
